### ISSUE TITLE
Commit Frequency

### ISSUE THREAD

**Issue by bh418v** [CodeWhisperer88/Telegram-bot#1]
-database.py
The `commit()` method is called after each operation in `set_engine`, which may lead to excessive disk I/O. Consider optimizing the commit frequency based on the requirements of your application.

**Comment by CodeWhisperer88** [comment]
Right.
Actually, this is an old codebase and I didn't update this repo.
Thanks for your issue.

**Comment by bh418v** [comment]
Oh, I understand.
Actually, I'm working on a similar project right now.
So I hope to cooperate with you in this field.
